"""Circle/ellipse node shape recognition — the Phase 3 "known limitation"
being closed here (see adapters/diagram/README.md, "Known limitations"):
previously only rectangle and diamond node shapes were recognized at all;
anything round was silently missed (never emitted as a region, not even at
low confidence).

This test would fail against the adapter before this change: every
assertion below about `node-circle` regions existing, being confidence-
scored (not hardcoded), OCR'd, and not duplicated depends on the new
ellipse-fitting branch in adapters/diagram/adapter.py._detect_nodes and its
companion dedup pass. Uses tests/fixtures/flowchart_with_circle.png,
generated by tests/fixtures/generate_diagram_fixture_shapes.py specifically
to exercise this: an ellipse ("Start") and a true circle ("End") alongside
the pre-existing rectangle/diamond shapes.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

FIXTURE = ROOT / "tests" / "fixtures" / "flowchart_with_circle.png"


def _build():
    from adapters.diagram.adapter import build_artifact

    return build_artifact(FIXTURE)


def test_ellipse_and_circle_nodes_are_detected_as_node_circle():
    artifact = _build()
    nodes = [r for r in artifact["regions"] if r["type"] == "node"]
    circles = [n for n in nodes if n["shape"] == "node-circle"]

    assert len(circles) == 2, (
        f"expected exactly 2 node-circle regions (the ellipse 'Start' and the circle 'End'), "
        f"got {len(circles)}: {[(n['shape'], n['text']) for n in nodes]}"
    )
    # Also still recognizes the rectangle and diamond in the same image —
    # the new branch must not have displaced the existing detection paths.
    assert any(n["shape"] == "node" and n["text"] == "Approve" for n in nodes), "rectangle node not detected"
    assert any(n["shape"] == "node-decision" for n in nodes), "diamond node not detected"
    assert len(nodes) == 4, f"expected exactly 4 total node regions, got {len(nodes)}"


def test_node_circle_confidence_is_a_real_signal_not_hardcoded():
    """Confidence must come from the actual ellipse-fit quality
    (adapter._ellipse_confidence, driven by adapter._ellipse_fit_error), not
    a constant — and it must sit in the documented node-confidence range,
    below a perfect rectangle's ceiling (0.97) since the geometric test for
    "this is an ellipse" is a softer, curve-fit-based judgment than the
    rectangle's hard axis-alignment + fill-ratio test.
    """
    from adapters.diagram.adapter import ELLIPSE_FIT_ERROR_MAX, ELLIPSE_FIT_ERROR_TIGHT, _ellipse_confidence

    artifact = _build()
    circles = [r for r in artifact["regions"] if r["shape"] == "node-circle"]
    assert circles, "expected at least one node-circle region to check confidence on"
    for region in circles:
        assert 0.75 <= region["confidence"] <= 0.95, f"node-circle confidence {region['confidence']} outside expected band"

    # The confidence function itself is monotonic in fit error -- a cleaner
    # fit must never score lower than a sloppier one. This is the actual
    # "real signal, not a hardcoded number" property being tested.
    tight = _ellipse_confidence(ELLIPSE_FIT_ERROR_TIGHT)
    loose = _ellipse_confidence(ELLIPSE_FIT_ERROR_MAX)
    mid = _ellipse_confidence((ELLIPSE_FIT_ERROR_TIGHT + ELLIPSE_FIT_ERROR_MAX) / 2)
    assert tight > mid > loose, f"expected strictly decreasing confidence as fit error grows, got {tight}, {mid}, {loose}"


def test_node_circle_labels_are_ocrd():
    """Both round-node labels ('Start', 'End') should be readable — proves
    the shape-aware OCR inset (adapter._ellipse_label_bbox) actually works,
    not just that shape classification works. A raw bbox crop for a curved
    shape was measured to make Tesseract return nothing at all for these
    exact labels before the inset was added.
    """
    artifact = _build()
    circles = {r["text"] for r in artifact["regions"] if r["shape"] == "node-circle"}
    assert circles == {"Start", "End"}, f"expected OCR'd labels {{'Start', 'End'}}, got {circles}"


def test_node_circle_regions_are_not_duplicated_by_inner_outer_contour():
    """A drawn ring (any closed shape's outline) produces two contours --
    outer and inner edge of the stroke -- and both can independently pass
    the ellipse checks. Without dedup this fixture would report 4
    node-circle regions (2 per round shape) instead of 2.
    """
    artifact = _build()
    circle_bboxes = []
    # Region objects don't carry bbox in the schema, so re-run detection
    # directly to check the pre-schema node list, which is where dedup happens.
    from adapters.diagram.adapter import _detect_nodes, _load_binary

    nodes = _detect_nodes(_load_binary(FIXTURE))
    circle_nodes = [n for n in nodes if n["shape"] == "node-circle"]
    assert len(circle_nodes) == 2, f"expected dedup down to 2 node-circle candidates, got {len(circle_nodes)}: {circle_nodes}"


def test_edges_still_resolve_to_real_nodes_including_circle_targets():
    """The 'no' branch in the fixture terminates at the circle node -- make
    sure edge reconstruction and the edges-reference-existing-nodes check
    both work when one endpoint of an edge is a node-circle, not just a
    rectangle/diamond.
    """
    artifact = _build()
    check = next(c for c in artifact["checks"] if c["name"] == "edges-reference-existing-nodes")
    assert check["passed"] is True, check["detail"]

    edges = [r for r in artifact["regions"] if r["type"] == "edge"]
    assert len(edges) == 3, f"expected 3 edges (start->decision, yes->approve, no->end), got {len(edges)}"


if __name__ == "__main__":
    import pytest

    raise SystemExit(pytest.main([__file__, "-v"]))
